routes/web.php
<?php

use App\Http\Controllers\BerandaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NovelController;
use App\Http\Controllers\SewaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BerandaController::class,'index']);
Route::get('/detail/{id}', [BerandaController::class,'show'])->name('detail');

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [BerandaController::class, 'dashboard']);
    Route::resource('sewa', SewaController::class);
    Route::group(['middleware' => 'cek_login:admin'], function () {
        Route::resource('novel', NovelController::class);
    });
    Route::group(['middleware' => 'cek_login:user'], function () {
        Route::post('sewa/konfirmasi/{id}',[SewaController::class, 'konfirmasi'])->name('konfirmasi');
        Route::post('sewa/kembalikan/{id}',[SewaController::class, 'kembalikan'])->name('kembalikan');
        Route::post('detail/sewa/{id}',[SewaController::class, 'store'])->name('sewa.sewa');
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/novel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class novel extends Model
{
    use HasFactory;
    protected $table = 'novel';
    protected $fillable = [
        'judul',
        'harga',
        'status',
        'gambar',
        'deskripsi',
    ];
}

app/Http/Controllers/NovelController.php
<?php

namespace App\Http\Controllers;

use App\Models\novel;
use App\Http\Requests\StorenovelRequest;
use App\Http\Requests\UpdatenovelRequest;
use Illuminate\Http\Request;

class NovelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = novel::all();
        return view('admin.novel.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.novel.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorenovelRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $message = [
            'required' => ':attribute wajib diisi!!!',
            'min' => ':attribute harus diisi minimal :min karakter!!!',
            'max' => ':attribute harus diisi maksimal :max karakter!!!',
            'date' => ':attribute harus diisi tanggal',
            'numeric' => ':attribute harus diisi angka'
        ];

        $this->validate($request, [
            'judul' => 'required',
            'deskripsi' => 'required',
            'harga' => 'required|numeric',
            'gambar' => 'required',
            'gambar.*' => 'mimes:jpg,jpeg,bmp,png,gif,svg',
        ], $message);

        $gambar = $request->file('gambar');
        $judul = $request->judul;
        $gambarnovel = $judul . '.' . $gambar->extension();
        $gambar->move(public_path('images'), $gambarnovel);
        novel::create($request->except(['gambar','status'])+[
            'status' => 'Tersedia',
            'gambar' => $gambarnovel
        ]);
        return redirect('novel')->with('success', 'Data novel berhasil ditambahkan!!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\novel  $novel
     * @return \Illuminate\Http\Response
     */
    public function show(novel $novel)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\novel  $novel
     * @return \Illuminate\Http\Response
     */
    public function edit(novel $novel)
    {
        return view('admin.novel.edit',compact('novel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatenovelRequest  $request
     * @param  \App\Models\novel  $novel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, novel $novel)
    {
        $message = [
            'required' => ':attribute wajib diisi!!!',
            'min' => ':attribute harus diisi minimal :min karakter!!!',
            'max' => ':attribute harus diisi maksimal :max karakter!!!',
            'date' => ':attribute harus diisi tanggal',
            'numeric' => ':attribute harus diisi angka'
        ];

        $this->validate($request, [
            'judul' => 'required',
            'deskripsi' => 'required',
            'harga' => 'required|numeric',
            'gambar.*' => 'mimes:jpg,jpeg,bmp,png,gif,svg',
        ], $message);

        if (!empty($request->file('gambar'))) {
            unlink(public_path('images') . '/' . $novel->gambar);
            $gambar = $request->file('gambar');
            $judul = $request->judul;
            $gambarnovel = $judul . '.' . $gambar->extension();
            $gambar->move(public_path('images'), $gambarnovel);

            novel::where('id', $novel->id)
                ->update($request->except(['gambar'])+[
                    'gambar' => $gambarnovel
                ]);
        }
        novel::where('id', $novel->id)
                ->update($request->except(['_token','_method']));
        return redirect('novel')->with('success', 'Data novel berhasil diubah!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\novel  $novel
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = novel::findOrFail($id);
        unlink(public_path('images') . '/' . $data->gambar);
        $data->delete();
        return redirect('novel')->with('success', 'Data novel berhasil dihapus!!!');
    }
}

resources/views/admin/novel/create.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Tambah Novel</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Data Novel</a></li>
                        <li class="breadcrumb-item active">Tambah Novel</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Form Input</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('novel.store')}}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="judul">Judul</label>
                                <input type="text" id="judul" name="judul" class="form-control @error('judul') is-invalid @enderror" value="{{ old('judul') }}" placeholder="Masukkan Judul Novel" required>
                                @error('judul')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="deskripsi">Deskripsi</label>
                                <textarea id="deskripsi" name="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" rows="4" value="{{ old('deskripsi') }}" required></textarea>
                                @error('deskripsi')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="harga">Harga Sewa/Hari</label>
                                <input type="number" id="harga" name="harga" value="{{ old('harga') }}" class="form-control @error('harga') is-invalid @enderror" placeholder="Masukkan Harga" required>
                                @error('harga')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="gambar">Cover Novel</label>
                                <input type="file" class="form-control @error('gambar') is-invalid @enderror" id="gambar" name="gambar" required>
                                @error('gambar')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <a href="{{url('novel')}}" class="btn btn-secondary">Kembali</a>
                            <button type="submit" class="btn btn-success float-right">Simpan</button>
                        </form>
                    </div>
                <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/admin/novel/edit.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Novel</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Data Novel</a></li>
                        <li class="breadcrumb-item active">Edit Novel</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Form Input</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('novel.update', $novel->id)}}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="judul">Judul</label>
                                <input type="text" id="judul" name="judul" class="form-control @error('judul') is-invalid @enderror" value="{{ $novel->judul }}" placeholder="Masukkan Judul Novel" required>
                                @error('judul')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="deskripsi">Deskripsi</label>
                                <textarea id="deskripsi" name="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" rows="4" value="{{ $novel->deskripsi }}" required>{{ $novel->deskripsi }}</textarea>
                                @error('deskripsi')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="harga">Harga Sewa/Hari</label>
                                <input type="number" id="harga" name="harga" value="{{ $novel->harga }}" class="form-control @error('harga') is-invalid @enderror" placeholder="Masukkan Harga" required>
                                @error('harga')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="gambar">Cover Novel</label>
                                <input type="file" class="form-control" id="gambar" name="gambar" value="{{$novel->gambar}}">
                                <img src="{{ url('images') }}/{{$novel->gambar}}" alt="{{$novel->judul}}" width="200">
                            </div>
                            <a href="{{url('novel')}}" class="btn btn-secondary">Kembali</a>
                            <button type="submit" class="btn btn-success float-right">Simpan</button>
                        </form>
                    </div>
                <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection

resources/views/admin/novel/index.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Data Novel</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Data Novel</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('novel.create')}}" class="btn btn-success">Tambah Novel</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Cover</th>
                                        <th>Judul</th>
                                        <th>Deskripsi</th>
                                        <th>Harga</th>
                                        <th>Status</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 0; @endphp
                                    @foreach($data as $data)
                                    @php $no++; @endphp
                                    <tr>
                                        <td>{{$no}}</td>
                                        <td>
                                            <img src="{{ url('images') }}/{{$data->gambar}}" alt="{{$data->judul}}" width="100">
                                        </td>
                                        <td>{{$data->judul}}</td>
                                        <td>{{$data->deskripsi}}</td>
                                        <td>{{$data->harga}}/Hari</td>
                                        <td>{{$data->status}}</td>
                                        <td>
                                            <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('novel.destroy', $data->id) }}" method="POST">
                                                <a href="{{ route('novel.edit', $data->id)}}" class="btn btn-warning mb-3"><i class=" fas fa-edit"></i> Edit</a>
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger mb-3"><i class=" fas fa-trash"></i> Hapus</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                <!-- /.card -->
                </div>
            <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@endsection